services:
  postgres:
    image: postgres
    container_name: calorie_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calorie_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata-vol:/var/lib/postgresql/data

volumes:
  pgdata-vol:
